### ISSUE TITLE
Resume ChinaEye after disable

### ISSUE THREAD

**Issue by cqx931** [dhowe/ChinaEye#12]
The current popup has nothing clickable after ChineEye is disabled.
![image](https://cloud.githubusercontent.com/assets/3056154/21430115/bb0b1a04-c89c-11e6-99cf-ac4afa6634dd.png)

**Comment by dhowe** [comment]
Should be able to click the same button to re-enable (like adn)...

**Comment by cqx931** [comment]
https://github.com/dhowe/ChinaEye/pull/13 fixed
