### ISSUE TITLE
Better Design for Pop up menu

### ISSUE THREAD

**Issue by cqx931** [dhowe/ChinaEye#18]
1. Better Button CSS
2. Wider Pop up
3. "Disable ChinaEye on this page" / "Resume ChinaEye on this page"
4. Any other content for the release?

**Comment by dhowe** [comment]
5. 'About' button that links to ChinaEye webpage

**Comment by cqx931** [comment]
Does ChinaEye already have a webpage? What's the link?

**Comment by dhowe** [comment]
For now use: http://rednoise.org/daniel/detail.html#chinaeye (which we should update, adding images, etc, as we add features)

**Comment by dhowe** [comment]
Button above should be 'for this site' or 'for this search' (see  #29 )

**Comment by cqx931** [comment]
done
