### ISSUE TITLE
Feature: Icon should change on pages where CE is blocking content 

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#22]
not sure design-wise, but I think we need 2 or 3 versions of the icon:

1. enabled/not-blocking (normal case)
2. enabled/blocking (attention-getting)
3. disabled (gray)

**Comment by cqx931** [comment]
A few design options:
![image](https://cloud.githubusercontent.com/assets/3056154/22860644/e009c1aa-f13e-11e6-8f75-f3465d93ad1f.png)

**Comment by cqx931** [comment]
done. https://github.com/dhowe/ChinaEye/pull/31
