### ISSUE TITLE
Feature: Show individual server responses in menu

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#23]
better design needed

![screen shot 2017-02-11 at 2 02 25 pm](https://cloud.githubusercontent.com/assets/737638/22851612/c0cbcc2a-f062-11e6-9fda-24bf5afd50ae.png)

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/23157912/f7e86f0e-f857-11e6-8444-95698be40d76.png)

**Comment by cqx931** [comment]
Do we only shows the server info if the page is blocked?

**Comment by dhowe** [comment]
Looks really good!
No, we can show server info whenever the user clicks on the menu
'Disable for search' should only activate when the user has searched
Where does the 'great firewall of china' link to?

**Comment by cqx931** [comment]
Currently I "Disable for search" only shows up if ChinaEye is on search result page and there it is active for search.
If the user search on a search engine and the keyword matches with one of the triggers, the page won't be checked from the server at all. Should the server response display collapse for this case or should ChinaEye always check this info?
I suppose "great firewall of china" should link to `http://www.greatfirewallofchina.org/` as we are getting the server info from them.

**Comment by dhowe** [comment]
> "Disable for search" only shows up if ChinaEye is on search result page

Hmm, maybe for search pages we just show the green for all servers (since we know they are not blocked), but don't actually do the search

>  "great firewall of china" should link to http://www.greatfirewallofchina.org/

Lets move the great firewall link to the bottom, and make it smaller

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/23171553/bf3dcb3c-f88d-11e6-8040-c982a80bcad2.png)

**Comment by dhowe** [comment]
Cool. 
So are we disabling by site (hostname) now?

**Comment by cqx931** [comment]
yes, either by hostname or by search keyword.

**Comment by cqx931** [comment]
This feature is now live: https://github.com/dhowe/ChinaEye/pull/36
