### ISSUE TITLE
Check TODO: items in source

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#26]
some questions, some suggested changes... some for discussion

**Comment by cqx931** [comment]
> TODO:do some valid keywords have only one part, or should we ignore them as invalid

If a keyword only have one part, it is still valid, it just means that it doesn't have a corresponding English translation in the document.

**Comment by dhowe** [comment]
one questions like this are answered, feel free to remove the corresponding TODO at your convenience

**Comment by cqx931** [comment]
> // TODO: if just installed, how can there be triggers in local storage?

https://github.com/dhowe/ChinaEye/pull/31/commits/f370d7880978661f664f7972f8d374fb16ad7ced

> // TODO: make sure that our style tag is not being added multiple times on the same page

https://github.com/dhowe/ChinaEye/pull/31/commits/f7fad0580fef36b862c8e02fe0e6ba0dd0bae0e4

all done, please check.
