### ISSUE TITLE
Allow users to use CE without redacting the page

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#28]
I'm not sure how this should work exactly, but there needs to be an option for users (if they so choose)  to keep CE enabled, but still view their favorite websites without redaction, even if they are blocked. This is sort of an info-only mode: CE still checks the page, but only changes the icon if blocked (and if the menu is clicked, shows the various server responses).

**Comment by cqx931** [comment]
https://github.com/dhowe/ChinaEye/pull/34

Added Info mode.(Icon is not showing correctly yet, see:https://github.com/dhowe/ChinaEye/issues/35 ) Please check
