### ISSUE TITLE
Add button to menu for disabling CE for entire site

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#29]
in fact, maybe this should just replace what we have now, as most blocks will be related to sites, rather than specific pages

but, if it is a search, then we should disable only for that search.

so we need lists (in local storage) for whitelistedSites, whitelistedPages (?), and whitelistedSearches

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ChinaEye/pull/33
For now I have added whitelistedSites and whitelistedSearches.
For the performance of buttons in popup.html, please see  https://github.com/dhowe/ChinaEye/issues/20 UI - popup
