### ISSUE TITLE
Should we store the blocking status of all the tabs in current Window?

### ISSUE THREAD

**Issue by cqx931** [dhowe/ChinaEye#35]
https://github.com/dhowe/ChinaEye/blob/master/js/background.js#L290
The icon should be updated whenever the current tab changes, but it doesn't make sense to run through the keyword and page check again to get the blocking status of a specific tab that has already been loaded.

```
tabId: 
{
tabUrl : url,
blockingStatus: status
}

```

**Comment by dhowe** [comment]
yes, good plan

**Comment by cqx931** [comment]
Checked in here: https://github.com/dhowe/ChinaEye/pull/36
