### ISSUE TITLE
Issue with "https"

### ISSUE THREAD

**Issue by cqx931** [dhowe/ChinaEye#37]
If the testing url is `https://developer.chrome.com/extensions/tabs#method-get`,
Great Firewall of China returns "An error occured - please try again later. If the error continues to occur, please contact the webmaster."

If I try the same page with http instead of https, the page work.
But when I tried other pages with https (Facebook, gmail...), I don't see this error.

**Comment by dhowe** [comment]
Interesting. Same on their interface: http://www.greatfirewallofchina.org/
Can you file a bug or send them an email (just as a normal user) ?

**Comment by cqx931** [comment]
I I have written an email to them, will report back when I get the response.

**Comment by cqx931** [comment]
No response up to this point....

**Comment by dhowe** [comment]
maybe resend?

**Comment by cqx931** [comment]
- [x] Check http:// if https:// doesn't work

- [x] Add a note for error scenario
