### ISSUE TITLE
Design for pages where we don't check servers

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#39]
E.g., `chrome://` pages. Doesn't work to say 'pending' as the wait would be forever... 

![image](https://cloud.githubusercontent.com/assets/737638/23355561/43859cbc-fd11-11e6-8e2e-e6860d021336.png)

Since we know such pages are not blocked, we might want to just show green for servers, but perhaps with some kind of note?

Another option (below) would be to simply hide (in the content-script) the server options for such pages (I think I like this better, as the other could be misleading).

![image](https://cloud.githubusercontent.com/assets/737638/23357550/3e930d5e-fd19-11e6-9964-1544507b2055.png)

**Comment by dhowe** [comment]
or maybe a narrower version of above...

**Comment by cqx931** [comment]
I just collapsed the server info. I prefer to have the menu always in the same width...
https://github.com/dhowe/ChinaEye/pull/42
