### ISSUE TITLE
Handle 'timeout' fails appropriately

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#40]
In [this case](http://time.com/4672988/the-sleep-cure-fountain-of-youth/), on Chrome, ChinaEye shows the page redacted, but GFW shows 'timeout'. Is this a valid response?

If so, perhaps it should get a yellow color, but not redacted? Same I think for anytime ANY of the servers is not green.

![image](https://cloud.githubusercontent.com/assets/737638/23357759/21e70894-fd1a-11e6-80ea-31730fff6b7f.png)

**Comment by cqx931** [comment]
https://github.com/dhowe/ChinaEye/blob/master/js/background.js#L438
Currently, ChinaEye only block a page if there are more than two servers failed in the test. When I test the case on greatfirewallofchina.org, I got all fails as result. Can the timeout result be some server issues of Greatfirewallofchina? 
I have added a yellow tag to display the server result if it is neither "fail" nor "ok".

**Comment by cqx931** [comment]
This can be closed for now.
