### ISSUE TITLE
Popup got "undefined" blocking status from background script when the script got checked with different protocol

### ISSUE THREAD

**Issue by cqx931** [dhowe/ChinaEye#48]
Result in wrong display of server info and buttons.
![image](https://cloud.githubusercontent.com/assets/3056154/24260981/64ef68c4-1030-11e7-88b3-815b1e9aa9af.png)

This seems to happen consistently on certain pages, such as:
https://hk.yahoo.com/?p=us

**Comment by dhowe** [comment]
Is this related to the long-lived messaging issue?

**Comment by cqx931** [comment]
Not for this issue...Please see fix here: https://github.com/dhowe/ChinaEye/pull/49
