### ISSUE TITLE
Add 'recheck now' button to menu interface

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#52]
Should first call:

   `Cache.clear(key);`

And then treat as a normal request (since the cache is cleared, the real server request will then be made)

**Comment by dhowe** [comment]
something like: 

![image](https://cloud.githubusercontent.com/assets/737638/24329462/7ad0d518-123a-11e7-80f1-bc5aee4408e9.png)

**Comment by cqx931** [comment]
![image](https://cloud.githubusercontent.com/assets/3056154/24329531/12ddf6c8-123c-11e7-89e4-00bbdd1d6513.png)

Maybe put it in the section above? In this way, the grouping can better indicate that it's the servers that will be rechecked.

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ChinaEye/pull/53

**Comment by dhowe** [comment]
Works well, however we need some kind of loading animation, otherwise it is not clear that the software is being done. Can we change the OK/FAIL icons to a little spinning circle (or some other easy indication that the check is being done)?

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ChinaEye/pull/56

- Change the pending tag to an loading gif
- Clear server info when clicking "recheck" button.

**Comment by cqx931** [comment]
This one can be closed
