### ISSUE TITLE
Make clear that a search is blocked in Info-mode

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#54]
In the result below, the search term is blocked, but there is no indication in the menu (only the icon which is hard to understand). If this is a quick fix, then lets add it to v1.0. If not, then you can push it to v1.1 (mark with 'next-tasks' milestone)

![screen shot 2017-03-27 at 12 36 52 pm](https://cloud.githubusercontent.com/assets/737638/24341245/f93400a0-12ea-11e7-8ac2-f4bdb1a8eec6.png)

**Comment by cqx931** [comment]
What you described doesn't seem to be only applied to info mode, it is showing the blocked keyword in popup window.
It should be a quick fix, but more of a design issue. How about something like this:
![image](https://cloud.githubusercontent.com/assets/3056154/24345435/b538bff4-1302-11e7-928d-fa765dae68fd.png)

**Comment by cqx931** [comment]
Option 2
![image](https://cloud.githubusercontent.com/assets/3056154/24346385/ad71403a-1306-11e7-9322-475ac184922a.png)

**Comment by cqx931** [comment]
or it should be "The above keyword is blocked within mainland China"?

**Comment by dhowe** [comment]
Good -- I like option 2. And yes, it should be "Your search keyword is blocked in mainland China!"

**Comment by cqx931** [comment]
https://github.com/dhowe/ChinaEye/commit/58b8e8a2a6699f7b79309d45c77500c147c6be5a
