### ISSUE TITLE
Check width/alignment of buttons and result labels

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#55]
![image](https://cloud.githubusercontent.com/assets/737638/24341665/d257e516-12ed-11e7-8ce8-3166f537355c.png)

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/ChinaEye/commit/756fddc5f0a11294b00c476c5d11fe3655aadd6a
![image](https://cloud.githubusercontent.com/assets/3056154/24355140/68f4140c-1327-11e7-8460-20e4b7ff8693.png)
