### ISSUE TITLE
Server check hangs loading disabled search

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#57]
appears to hang indefinitely, until I re-enable the search

![image](https://cloud.githubusercontent.com/assets/737638/24352871/cc704ec4-131d-11e7-8b94-d4a74190b384.png)

**Comment by cqx931** [comment]
Fixed in https://github.com/dhowe/ChinaEye/pull/60/commits/52344a198c12d4dc059b20187e41b4d23d1f8151
Please verify
