### ISSUE TITLE
How is this installed/how does it work?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [dhowe/ChinaEye#6]
Hi there, 

Is this meant to be an educational tool to emphasize the importance of privacy and an open web? What browser is this for? It sounds fascinating in any case.

Thanks for your time.

**Comment by cqx931** [comment]
ChinaEye allows users to experience the web as if living in China. ChinaEye hides all content on sites that are blocked in China. It does this via real-time lookup on a number of proxy sites in China (Beijing, Shenzen, Mongolia, HeilongJiang, Yunnan, etc). If the page is blocked in one or more of these locations, the page appears with content obscured. Similarly, when searching, if a particular search term is censored, then the search results will be obscured as well.

For now, ChinaEye only works in chrome and it is still at very early stage of developing.
Thanks for your interest in the project!

**Comment by dhowe** [comment]
You can now install ChinaEye via the Chrome Store [here](https://chrome.google.com/webstore/detail/chinaeye/kbkejkbhaiggcfnalkdlphlikillhlpf)
