### ISSUE TITLE
Create (non-developer) FAQ

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#65]
- Document list-sources (with link to the list itself)
- Document where our result come from

**Comment by cqx931** [comment]
ChinaEye blocks a search result page if the search keywords match with an entry from a keyword list ([raw file](https://github.com/jasonqng/chinese-keywords/blob/master/csv/no-dummy-vars-for-categories-and-themes_only-sensitive-words.csv)). The list is combined from 13 existing lists online by  [Jason Q. Ng](www.jasonqng.com/). Please refer to [this link](https://citizenlab.org/2014/12/repository-censored-sensitive-chinese-keywords-13-lists-9054-terms/) if you want to know more about the list.

For webpages that are not search result pages, Chinaeye will check the page domain in http://www.greatfirewallofchina.org/ and block the page if none of the servers from greatfirewallofchina can have access to the domain.

*greatfirewallofchina for now.

**Comment by dhowe** [comment]
Looks good. Please add to FAQ here: https://github.com/dhowe/chinaeye/wiki
