### ISSUE TITLE
Question on 'disable' for search engines

### ISSUE THREAD

**Issue by dhowe** [dhowe/ChinaEye#73]
Are we disabling for the site or for the search query?

**Comment by cqx931** [comment]
Do you see a "disable" button?
There should always be a "Disable for this site" button and also a "Disable for this search" button for search engines if the current search is triggering a block.

**Comment by dhowe** [comment]
So I think what is happening is that b/c the search engine itself is blocked, one never sees the 'disable for this search' button, even if the search itself would be blocked as well. 

And then once 'disabled for the site' is clicked, it is disabled for all search queries as well... 

So there is no way, currently, to say disable for the site, unless the search is blocked...

Is all this correct?

**Comment by cqx931** [comment]
You can only see "disable for this search" button if the search query is a match with our list.
But this button is not visible, for example, if you search "credit card" on google, because the search itself can't trigger a block.
![image](https://user-images.githubusercontent.com/3056154/32915644-96282710-cae7-11e7-9bce-f8d4dbe9aa9f.png)

**Comment by dhowe** [comment]
Right, but for the case where BOTH the site and query are blocked, one sees only the 'disable for this site' button (same search as yours below)

![image](https://user-images.githubusercontent.com/737638/32915878-548510f2-cb55-11e7-98c8-ade85db6cf92.png)

**Comment by cqx931** [comment]
Can you provide your search link? I can still see "disable for this search" if I change my search engine to google.com.hk

**Comment by dhowe** [comment]
So your query is being blocked, but the site is showing as blocked for me...

https://www.google.com.hk/search?ei=FvwNWry3MIKy0ATn-6DoBg&q=grass+mud+horse+&oq=grass+mud+horse

**Comment by cqx931** [comment]
For the link above, the issue seems be caused by the extra "+" before "oq=grass+mud+horse"
Please check the fix here: https://github.com/dhowe/ChinaEye/pull/74
