### ISSUE TITLE
Update wordlist

### ISSUE THREAD

**Issue by cqx931** [dhowe/ChinaEye#79]
by China Digital times
https://docs.google.com/spreadsheets/d/1UTP9MU80r_N5WPhQ5-4AjM0ebW1eMxyDlRe_vaYy9IM/edit#gid=0

**Comment by dhowe** [comment]
excellent -- how much work to integrate these?

**Comment by cqx931** [comment]
Just did a quick check, words from 2014-08-01 are not integrated in our current list, merging new words to the list should be pretty quick.

English Translations are only available up to 2017-07-15

**Comment by cqx931** [comment]
Please check: https://github.com/dhowe/ChinaEye/pull/80
