### ISSUE TITLE
Unable to match the keyword after page refresh

### ISSUE THREAD

**Issue by cqx931** [dhowe/ChinaEye#8]
To reproduce

0.switch on `showLogs` in background.js
1.Go to google and type "23", The status should be detected as "Block"
2.Now refresh the page. In the background console, the qRegex doesn't return a match from the same url.
3.Refresh the page again, the qRegex works again.

<img width="545" alt="screen shot 2016-12-22 at 1 40 17 pm" src="https://cloud.githubusercontent.com/assets/3056154/21416237/385f10ba-c84c-11e6-8135-7c632f85a773.png">

**Comment by dhowe** [comment]
Not sure what the issue is here (or how to recreate)

**Comment by cqx931** [comment]
Please check the new fix 
https://github.com/dhowe/ChinaEye/pull/9

**Comment by dhowe** [comment]
Check 497a4ce981

**Comment by cqx931** [comment]
Great it works!
